## 練習時間
資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？

#### Ex: 如何知道資料的 row 數以及 column 數、有什麼欄位、多少欄位、如何截取部分的資料等等

有了對資料的好奇之後，我們又怎麼通過程式碼來達成我們的目的呢？

#### 可參考該[基礎教材](https://bookdata.readthedocs.io/en/latest/base/01_pandas.html#DataFrame-%E5%85%A5%E9%97%A8)或自行 google

In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
# 設定 data_path
dir_data = './data/'

In [3]:
f_app = os.path.join(dir_data, 'application_train.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)

Path of read in data: ./data/application_train.csv

### 如果沒有想法，可以先嘗試找出剛剛例子中提到的問題的答案
#### 資料的 row 數以及 column 數

In [5]:
# .info()確認檔案資訊 ,RangeIndex = rows count , Columns = columns count
app_train.info()
# .shape 顯示(rows count,columns count)
app_train.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Columns: 122 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(65), int64(41), object(16)
memory usage: 286.2+ MB

(307511, 122)

#### 列出所有欄位

In [11]:
#顯示第一列index 取消省略顯示限制
pd.set_option('display.max_columns', 122)
app_train.head(0)

Empty DataFrame
Columns: [SK_ID_CURR, TARGET, NAME_CONTRACT_TYPE, CODE_GENDER, FLAG_OWN_CAR, FLAG_OWN_REALTY, CNT_CHILDREN, AMT_INCOME_TOTAL, AMT_CREDIT, AMT_ANNUITY, AMT_GOODS_PRICE, NAME_TYPE_SUITE, NAME_INCOME_TYPE, NAME_EDUCATION_TYPE, NAME_FAMILY_STATUS, NAME_HOUSING_TYPE, REGION_POPULATION_RELATIVE, DAYS_BIRTH, DAYS_EMPLOYED, DAYS_REGISTRATION, DAYS_ID_PUBLISH, OWN_CAR_AGE, FLAG_MOBIL, FLAG_EMP_PHONE, FLAG_WORK_PHONE, FLAG_CONT_MOBILE, FLAG_PHONE, FLAG_EMAIL, OCCUPATION_TYPE, CNT_FAM_MEMBERS, REGION_RATING_CLIENT, REGION_RATING_CLIENT_W_CITY, WEEKDAY_APPR_PROCESS_START, HOUR_APPR_PROCESS_START, REG_REGION_NOT_LIVE_REGION, REG_REGION_NOT_WORK_REGION, LIVE_REGION_NOT_WORK_REGION, REG_CITY_NOT_LIVE_CITY, REG_CITY_NOT_WORK_CITY, LIVE_CITY_NOT_WORK_CITY, ORGANIZATION_TYPE, EXT_SOURCE_1, EXT_SOURCE_2, EXT_SOURCE_3, APARTMENTS_AVG, BASEMENTAREA_AVG, YEARS_BEGINEXPLUATATION_AVG, YEARS_BUILD_AVG, COMMONAREA_AVG, ELEVATORS_AVG, ENTRANCES_AVG, FLOORSMAX_AVG, FLOORSMIN_AVG, LANDAREA_AVG, LIVINGAPARTMENTS_AVG, LIVINGAREA_AVG, NONLIVINGAPARTMENTS_AVG, NONLIVINGAREA_AVG, APARTMENTS_MODE, BASEMENTAREA_MODE, YEARS_BEGINEXPLUATATION_MODE, YEARS_BUILD_MODE, COMMONAREA_MODE, ELEVATORS_MODE, ENTRANCES_MODE, FLOORSMAX_MODE, FLOORSMIN_MODE, LANDAREA_MODE, LIVINGAPARTMENTS_MODE, LIVINGAREA_MODE, NONLIVINGAPARTMENTS_MODE, NONLIVINGAREA_MODE, APARTMENTS_MEDI, BASEMENTAREA_MEDI, YEARS_BEGINEXPLUATATION_MEDI, YEARS_BUILD_MEDI, COMMONAREA_MEDI, ELEVATORS_MEDI, ENTRANCES_MEDI, FLOORSMAX_MEDI, FLOORSMIN_MEDI, LANDAREA_MEDI, LIVINGAPARTMENTS_MEDI, LIVINGAREA_MEDI, NONLIVINGAPARTMENTS_MEDI, NONLIVINGAREA_MEDI, FONDKAPREMONT_MODE, HOUSETYPE_MODE, TOTALAREA_MODE, WALLSMATERIAL_MODE, EMERGENCYSTATE_MODE, OBS_30_CNT_SOCIAL_CIRCLE, DEF_30_CNT_SOCIAL_CIRCLE, OBS_60_CNT_SOCIAL_CIRCLE, DEF_60_CNT_SOCIAL_CIRCLE, DAYS_LAST_PHONE_CHANGE, FLAG_DOCUMENT_2, FLAG_DOCUMENT_3, FLAG_DOCUMENT_4, FLAG_DOCUMENT_5, ...]
Index: []

#### 列出所有欄位 其他做法

In [15]:
# .columns 取得所有欄位
print(app_train.columns)

print('------------------------------')
#跑個迴圈 秀出來
index_list = app_train.columns
count = 0
for col in index_list:
    count += 1
    print(count, col)

Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='object', length=122)
------------------------------
1 SK_ID_CURR
2 TARGET
3 NAME_CONTRACT_TYPE
4 CODE_GENDER
5 FLAG_OWN_CAR
6 FLAG_OWN_REALTY
7 CNT_CHILDREN
8 AMT_INCOME_TOTAL
9 AMT_CREDIT
10 AMT_ANNUITY
11 AMT_GOODS_PRICE
12 NAME_TYPE_SUITE
13 NAME_INCOME_TYPE
14 NAME_EDUCATION_TYPE
15 NAME_FAMILY_STATUS
16 NAME_HOUSING_TYPE
17 REGION_POPULATION_RELATIVE
18 DAYS_BIRTH
19 DAYS_EMPLOYED
20 DAYS_REGISTRATION
21 DAYS_ID_PUBLISH
22 OWN_CAR_AGE
23 FLAG_MOBIL
24 FLAG_EMP_PHONE
25 FLAG_WORK_PHONE
26 FLAG_CONT_MOBILE
27 FLAG_PHONE
28 FLAG_EMAIL
29 OCCUPATION_TYPE
30 CNT_FAM_MEMBERS
31 REGION_RATING_CLIENT
32 REGION_RATING_CLIENT_W_CITY
33 WEEKDAY_APPR_PROCESS_START
34 HOUR_APPR_PROCESS_START
35 REG_REGION_NOT_LIVE_REGION
36 REG_REGION_NOT_WORK_REGION
37 LIVE_REGION_NOT_WORK_REGION
38 REG_CITY_NOT_LIVE_CITY
39 REG_CITY_NOT_WORK_CITY
40 LIVE_CITY_NOT_WORK_CITY
41 ORGANIZATION_TYPE
42 EXT_SOURCE_1
43 EXT_SOURCE_2
44 EXT_SOURCE_3
45 APARTMENTS_AVG
46 BASEMENTAREA_AVG
47 YEARS_BEGINEXPLUATATION_AVG
48 YEARS_BUILD_AVG
49 COMMONAREA_AVG
50 ELEVATORS_AVG
51 ENTRANCES_AVG
52 FLOORSMAX_AVG
53 FLOORSMIN_AVG
54 LANDAREA_AVG
55 LIVINGAPARTMENTS_AVG
56 LIVINGAREA_AVG
57 NONLIVINGAPARTMENTS_AVG
58 NONLIVINGAREA_AVG
59 APARTMENTS_MODE
60 BASEMENTAREA_MODE
61 YEARS_BEGINEXPLUATATION_MODE
62 YEARS_BUILD_MODE
63 COMMONAREA_MODE
64 ELEVATORS_MODE
65 ENTRANCES_MODE
66 FLOORSMAX_MODE
67 FLOORSMIN_MODE
68 LANDAREA_MODE
69 LIVINGAPARTMENTS_MODE
70 LIVINGAREA_MODE
71 NONLIVINGAPARTMENTS_MODE
72 NONLIVINGAREA_MODE
73 APARTMENTS_MEDI
74 BASEMENTAREA_MEDI
75 YEARS_BEGINEXPLUATATION_MEDI
76 YEARS_BUILD_MEDI
77 COMMONAREA_MEDI
78 ELEVATORS_MEDI
79 ENTRANCES_MEDI
80 FLOORSMAX_MEDI
81 FLOORSMIN_MEDI
82 LANDAREA_MEDI
83 LIVINGAPARTMENTS_MEDI
84 LIVINGAREA_MEDI
85 NONLIVINGAPARTMENTS_MEDI
86 NONLIVINGAREA_MEDI
87 FONDKAPREMONT_MODE
88 HOUSETYPE_MODE
89 TOTALAREA_MODE
90 WALLSMATERIAL_MODE
91 EMERGENCYSTATE_MODE
92 OBS_30_CNT_SOCIAL_CIRCLE
93 DEF_30_CNT_SOCIAL_CIRCLE
94 OBS_60_CNT_SOCIAL_CIRCLE
95 DEF_60_CNT_SOCIAL_CIRCLE
96 DAYS_LAST_PHONE_CHANGE
97 FLAG_DOCUMENT_2
98 FLAG_DOCUMENT_3
99 FLAG_DOCUMENT_4
100 FLAG_DOCUMENT_5
101 FLAG_DOCUMENT_6
102 FLAG_DOCUMENT_7
103 FLAG_DOCUMENT_8
104 FLAG_DOCUMENT_9
105 FLAG_DOCUMENT_10
106 FLAG_DOCUMENT_11
107 FLAG_DOCUMENT_12
108 FLAG_DOCUMENT_13
109 FLAG_DOCUMENT_14
110 FLAG_DOCUMENT_15
111 FLAG_DOCUMENT_16
112 FLAG_DOCUMENT_17
113 FLAG_DOCUMENT_18
114 FLAG_DOCUMENT_19
115 FLAG_DOCUMENT_20
116 FLAG_DOCUMENT_21
117 AMT_REQ_CREDIT_BUREAU_HOUR
118 AMT_REQ_CREDIT_BUREAU_DAY
119 AMT_REQ_CREDIT_BUREAU_WEEK
120 AMT_REQ_CREDIT_BUREAU_MON
121 AMT_REQ_CREDIT_BUREAU_QRT
122 AMT_REQ_CREDIT_BUREAU_YEAR

#### 截取部分資料

In [16]:
# DataFrame.loc [:數量, '篩出index']
app_train.loc[:10, ['SK_ID_CURR','NAME_CONTRACT_TYPE','AMT_REQ_CREDIT_BUREAU_YEAR']]

    SK_ID_CURR NAME_CONTRACT_TYPE  AMT_REQ_CREDIT_BUREAU_YEAR
0       100002         Cash loans                         1.0
1       100003         Cash loans                         0.0
2       100004    Revolving loans                         0.0
3       100006         Cash loans                         NaN
4       100007         Cash loans                         0.0
5       100008         Cash loans                         1.0
6       100009         Cash loans                         2.0
7       100010         Cash loans                         0.0
8       100011         Cash loans                         1.0
9       100012    Revolving loans                         NaN
10      100014         Cash loans                         0.0

#### 還有各種數之不盡的資料操作，重點還是取決於實務中遇到的狀況和你想問的問題，在馬拉松中我們也會陸續提到更多例子

In [17]:
# 篩出 AMT_INCOME_TOTAL > 500000的資料 
app_train.loc[app_train['AMT_INCOME_TOTAL'] > 500000]

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
51,100059,0,Cash loans,M,Y,Y,1,540000.0,675000.0,34596.0,675000.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.026392,-18632,-6977,-3904.0,-1937,7.0,1,1,0,1,1,0,Managers,3.0,2,2,TUESDAY,10,0,0,0,0,0,0,Services,0.311510,0.713355,0.309275,0.5309,0.2491,0.9811,0.7416,NaN,0.88,0.3793,0.4583,0.0000,0.3977,NaN,0.5878,NaN,0.0487,0.5410,0.2585,0.9811,0.7517,NaN,0.8862,0.3793,0.4583,0.0000,0.4067,NaN,0.6124,NaN,0.0516,0.5361,0.2491,0.9811,0.7451,NaN,0.88,0.3793,0.4583,0.0000,0.4046,NaN,0.5983,NaN,0.0498,NaN,block of flats,0.5149,Panel,No,2.0,0.0,2.0,0.0,-1285.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,1.0,0.0,0.0,3.0
59,100070,0,Cash loans,M,Y,Y,0,540000.0,1227901.5,46899.0,1129500.0,Unaccompanied,Working,Higher education,Widow,House / apartment,0.032561,-20544,-2091,-6846.0,-566,2.0,1,1,1,1,0,0,Managers,1.0,1,1,TUESDAY,14,0,0,0,0,0,0,Business Entity Type 3,NaN,0.653597,0.339288,0.0256,0.0000,0.9354,0.1160,0.0076,0.00,0.1172,0.1000,0.1417,0.0664,0.0202,0.0305,0.0039,0.0084,0.0063,0.0000,0.9136,0.0000,0.0006,0.0000,0.0690,0.0833,0.1250,0.0819,0.0055,0.0072,0.0000,0.0000,0.0104,0.0000,0.9136,0.0000,0.0015,0.00,0.0690,0.0833,0.1250,0.0815,0.0086,0.0070,0.0039,0.0013,reg oper account,block of flats,0.0058,"Stone, brick",No,0.0,0.0,0.0,0.0,-1377.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
319,100366,0,Revolving loans,M,Y,Y,0,765000.0,1350000.0,67500.0,1350000.0,Unaccompanied,Commercial associate,Higher education,Single / not married,House / apartment,0.002506,-11788,-3144,-5643.0,-3962,3.0,1,1,0,1,0,0,Managers,1.0,2,2,THURSDAY,7,0,0,0,1,1,0,Business Entity Type 3,0.421765,0.765981,0.511892,0.0330,0.0374,0.9831,0.7688,0.0093,0.00,0.0690,0.1250,0.1667,0.0087,0.0269,0.0327,0.0000,0.0252,0.0336,0.0388,0.9831,0.7779,0.0094,0.0000,0.0690,0.1250,0.1667,0.0089,0.0294,0.0341,0.0000,0.0266,0.0333,0.0374,0.9831,0.7719,0.0094,0.00,0.0690,0.1250,0.1667,0.0088,0.0274,0.0333,0.0000,0.0257,reg oper account,NaN,0.0336,Block,No,1.0,0.0,0.0,0.0,-151.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
332,100380,0,Cash loans,F,N,Y,0,630000.0,900000.0,57519.0,900000.0,Family,Working,Higher education,Married,House / apartment,0.072508,-15023,-1481,-3.0,-2483,NaN,1,1,0,1,0,0,High skill tech staff,2.0,1,1,SATURDAY,13,0,0,0,0,0,0,Business Entity Type 3,NaN,0.598937,NaN,0.0593,0.0650,0.9727,0.6260,0.0000,0.00,0.1207,0.1667,0.2083,0.0000,0.0483,0.0411,0.0000,0.0717,0.0504,0.0634,0.9717,0.6276,0.0000,0.0000,0.1034,0.1667,0.2083,0.0000,0.0441,0.0389,0.0000,0.0512,0.0599,0.0650,0.9727,0.6310,0.0000,0.00,0.1207,0.1667,0.2083,0.0000,0.0492,0.0418,0.0000,0.0732,reg oper account,block of flats,0.0664,"Stone, brick",No,0.0,0.0,0.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
391,100454,0,Revolving loans,M,Y,Y,3,607500.0,1350000.0,67500.0,1350000.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.032561,-13530,-3269,-987.0,-4360,2.0,1,1,0,1,0,0,Managers,5.0,1,1,THURSDAY,10,0,0,0,0,0,0,Other,NaN,0.623473,NaN,0.0608,0.0639,0.9503,0.3200,0.0168,0.16,0.1379,0.2083,0.2500,0.0622,0.0488,0.0886,0.0077,0.0253,0.0609,0.0663,0.9503,0.3466,0.0169,0.1611,0.1379,0.2083,0.2500,0.0636,0.0533,0.0923,0.0078,0.0268,0.0614,0.0639,0.9503,0.3291,0.0169,0.16,0.1379,0.2083,0.2500,0.0633,0.0496,0.0902,0.0078,0.0258,reg oper account,block of flats,0.0843,"Stone, brick",No,0.0,0.0,0.0,0.0,-2.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
622,100712,0,Cash loans,M,N,N,2,540000.0,1575000.0,43443.0,1575000.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.032561,-15111,-1247,-4063.0,-758,NaN,1,1,0,1,1,0,Managers,4.0,1,1,WEDNESDAY,11,0,0,0,0,0,0,Business Entity Type 3,NaN,0.788625,0.636376,0.0464,0.0322,0.9767,0.6804,0.0092,0.04,0.0345,0.3333,0.0417,0.0211,0.0681,0.0395,0.0000,0.0208,0.0473,0.0334,0.9767,0.6929,0.0093,0.0403,0.0345,0.3333,0.0417,0.0216,0.0744,0.0412,0.0000,0.0220,0.0468,0.0322,0.9767,0.6847,0.0093,0.04,0.0345,0.3333,0.0417,0.0214,0.0693,0.0402,0.0000,0.0212,org spec account,block of flats,0.0362,"Stone, brick",No,0.0,0.0,0.0,0.0,-2304.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,9.0,0.0,2.0
632,100722,0,Cash loans,M,Y,Y,0,540000.0,545040.0,26640.0,450000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.028663,-16194,-1321,-8752.0,-4617,0.0,1,1,1,1,0,1,NaN,2.0,2,2,FRIDAY,13,0,0,0,0,0,0,Agriculture,0.647140,0.681053,0.528093,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-2580.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
701,100810,0,Revolving loans,M,Y,Y,2,540000.0,900000.0,45000.0,900000.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.018801,-12643,-770,-83.0,-4126,13.0,1,1,0,1,0,0,Managers,4.0,2,2,MONDAY,10,0,0,0,0,0,0,Self-employed,0.515476,0.193497,0.424130,0.2495,0.1257,0.9940,0.9184,0.1220,0.24,0.2069,0.3750,0.4167,0.3106,0.2017,0.2564,0.0077,0.0071,0.2542,0.1305,0.9940,0.9216,0.1232,0.2417,0.2069,0.3750,0.4167,0.3177,0.2204,0.2671,0.0078,0.0075,0.2519,0.1257,0.9940,0.9195,0.1228,0.24,0.2069,0.3750,0.4167,0.3160,0.2052,0.2610,0.0078,0.0073,reg oper account,block of flats,0.2683,Panel,No,0.0,0.0,0.0,0.0,-457.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
930,101073,1,Cash loans,F,Y,N,0,540000.0,485640.0,44671.5,450000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.008474,-14122,-1397,-6768.0,-2999,18.0,1,1,0,1,0,0,Managers,2.0,2,2,THURSDAY,10,0,0,0,0,0,0,Trade: type 3,0.795851,0.286501,0.234015,0.0701,0.1709,0.9791,NaN,NaN,0.00,0.1379,0.1667,NaN,0.0282,NaN,0.0641,NaN,0.0298,0.0714,0.1774,0.9791,NaN,NaN,0.0000,0.1379,0.1667,NaN,0.0289,NaN,0.0668,NaN,0.0315,0.0708,0.1709,0.9791,NaN,NaN,0.00,0.1379,0.1667,NaN,0.0287,NaN,0.0653,NaN,0.0304,NaN,block of flats,0.0569,"Stone, brick",No,0.0,0.0,0.0,0.0,-2329.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1049,101218,0,Cash loans,M,Y,Y,0,522000.0,746280.0,59094.0,675000.0,Unaccompanied,State servant,Higher education,Married,House / apartment,0.072508,-20715,-504,-11795.0,-4027,2.0,1,1,0,1,1,0,Drivers,2.0,1,1,FRIDAY,13,0,0,0,0,0,0,Government,0.793142,0.767299,0.103449,0.1309,0.0498,0.9836,0.7688,0.0346,0.08,0.0345,0.6250,0.6667,0.0000,0.1067,0.1161,0.0039,0.0024,0.1334,0.0517,0.9836,0.7779,0.0349,0.0806,0.0345,0.6250,0.6667,0.0000,0.1166,0.1209,0.0039,0.0025,0.1322,0.0498,0.9836,0.7719,0.0348,0.08,0.0345,0.6250,0.6667,0.0000,0.1086,0.1181,0.0039,0.0024,reg oper account,block of flats,0.0918,Panel,No,1.0,0.0,1.0,0.0,-520.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,1.0,0.0,0.0,3.0
1064,101235,0,Revolving loans,F,N,Y,0,720000.0,1350000.0,67500.0,1350000.0,Unaccompanied,Pensioner,Higher education,Married,House / apartment,0.010147,-21030,365243,-322.0,-3814,NaN,1,0,0,1,0,0,NaN,2.0,2,2,THURSDAY,13,0,0,0,0,0,0,XNA,NaN,0.450422,NaN,0.0619,0.0604,0.9801,NaN,NaN,0.00,0.1379,0.1667,NaN,0.0972,NaN,0.0366,NaN,0.0000,0.0630,0.0626,0.9801,NaN,NaN,0.0000,0.1379,0.1667,NaN,0.0994,NaN,0.0381,NaN,0.0000,0.0625,0.0604,0.9801,NaN,NaN,0.00,0.1379,0.1667,NaN,0.0989,NaN,0.0372,NaN,0.0000,NaN,block of flats,0.0416,Panel,No,NaN,NaN,NaN,NaN,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1238,101461,0,Cash loans,M,Y,Y,0,810000.0,661500.0,37066.5,661500.0,Unaccompanied,Commercial associate,Secondary / secondary special,Married,House / apartment,0.072508,-21766,-5065,-11148.0,-1374,5.0,1,1,0,1,1,0,Drivers,2.0,1,1,SATURDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.827740,0.629307,0.593718,0.5134,0.3599,0.9796,0.7212,0.0000,0.56,0.4828,0.3333,0.3750,0.0000,0.4152,0.5012,0.0154,0.0069,0.5231,0.3735,0.9796,0.7321,0.0000,0.5639,0.4828,0.3333,0.3750,0.0000,0.4536,0.5221,0.0156,0.0073,0.5184,0.3599,0.9796,0.7249,0.0000,0.56,0.4828,0.3333,0.3750,0.0000,0.4224,0.5102,0.0155,0.0070,reg oper account,block of flats,0.3957,Panel,No,0.0,0.0,0.0,0.0,-1695.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
1316,101545,0,Cash loans,M,Y,Y,1,630000.0,1257255.0,53397.0,1156500.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.046220,-16202,-7639,-9109.0,-4110,2.0,1,1,0,1,1,1,Laborers,3.0,1,1,SUNDAY,12,0,0,0,0,1,1,Transport: type 2,NaN,0.757376,0.463275,0.0082,0.0000,0.9702,0.5920,0.0012,0.00,0.0690,0.0417,0.0417,0.0081,0.0067,0.0077,0.0000,0.0000,0.0084,0.0000,0.9702,0.6080,0.0012,0.0000,0.0690,0.0417,0.0417,0.0082,0.0073,0.0080,0.0000,0.0000,0.0083,0.0000,0.9702,0.5975,0.0012,0.00,0.0690,0.0417,0.0417,0.0082,0.0068,0.0079,0.0000,0.0000,reg oper account,block of flats,0.0067,"Stone, brick",No,0.0,0.0,0.0,0.0,-3329.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1450,101705,1,Revolving loans,M,N,Y,0,675000.0,270000.0,13500.0,270000.0,Family,Commercial associate,Higher education,Married,House / apartment,0.008625,-17188,-3203,-5678.0,-728,NaN,1,1,0,1,0,0,Managers,2.0,2,2,THURSDAY,12,0,0,0,0,1,1,Business Entity Type 3,NaN,0.273246,0.232725,0.2113,NaN,0.9786,NaN,NaN,0.16,0.1379,0.3333,NaN,NaN,NaN,0.2229,NaN,0.1369,0.2153,NaN,0.9786,NaN,NaN,0.1611,0.1379,0.3333,NaN,NaN,NaN,0.2323,NaN,0.1449,0.2134,NaN,0.9786,NaN,NaN,0.16,0.1379,0.3333,NaN,NaN,NaN,0.2269,NaN,0.1398,NaN,block of flats,0.1753,"Stone, brick",No,0.0,0.0,0.0,0.0,-683.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
1504,101769,0,Revolving loans,M,Y,Y,0,1080000.0,180000.0,9000.0,180000.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.072508,-13633,-5536,-3.0,-4971,7.0,1,1,0,1,0,0,NaN,2.0,1,1,FRIDAY,13,0,1,1,0,0,0,Business Entity Type 3,NaN,0.652924,0.456110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-491.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1568,101839,0,Cash loans,F,N,N,0,630000.0,562500.0,26064.0,562500.0,Unaccompanied,Commercial associate,Higher education,Single / not married,House / apartment,0.020713,-12141,-3511,-336.0,-3722,NaN,1,1,1,1,0,0,Sales staff,1.0,3,2,TUESDAY,13,0,0,0,0,0,0,Other,0.705785,0.444918,0.572683,0.2278,0.2182,0.9886,0.8436,0.0268,0.16,0.1034,0.3333,0.3750,0.1237,0.1816,0.2673,0.0193,0.1317,0.2321,0.2264,0.9886,0.8497,0.0271,0.1611,0.1034,0.3333,0.3750,0.1265,0.1983,0.2785,0.0195,0.1394,0.2300,0.2182,0.9886,0.8457,0.0270,0.16,0.1034,0.3333,0.3750,0.1259,0.1847,0.2721,0.0194,0.1344,reg oper account,block of flats,0.2535,"Stone, brick",No,2.0,1.0,2.0,1.0,-1.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1586,101857,0,Cash loans,F,N,Y,0,720000.0,1125000.0,44617.5,1125000.0,Unaccompanied,Commercial associate,Higher education,Widow,House / apartment,0.046220,-21630,-1059,-13.0,-1726,NaN,1,1,1,1,1,0,NaN,1.0,1,1,MONDAY,11,1,0,1,1,1,1,Other,0.882421,0.687675,0.256706,NaN,0.1848,0.9995,0.9932,NaN,0.64,0.1379,1.0000,1.0000,NaN,0.3522,0.5290,NaN,0.0810,NaN,0.1917,0.9995,0.9935,NaN,0.6445,0.1379,1.0000,1.0000,NaN,0.3848,0.5511,NaN,0.0857,NaN,0.1848,0.9995,0.9933,NaN,0.64,0.1379,1.0000,1.0000,NaN,0.3583,0.5385,NaN,0.0827,reg oper account,block of flats,0.5845,Monolithic,No,0.0,0.0,0.0,0.0,-664.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1644,101929,1,Revolving loans,F,Y,Y,0,697500.0,450000.0,22500.0,450000.0,Family,Working,Secondary / secondary special,Civil marriage,House / apartment,0.046220,-23299,-2550,-2591.0,-103,7.0,1,1,0,1,0,0,Medicine staff,2.0,1,1,WEDNESDAY,17,0,0,0,0,0,0,Medicine,NaN,0.696737,NaN,0.1237,0.0732,0.9896,NaN,NaN,0.12,0.1034,0.3333,0.3750,NaN,0.1009,0.0779,0.0000,NaN,0.1261,0.0760,0.9896,NaN,NaN,0.1208,0.1034,0.3333,0.3750,NaN,0.1102,0.0811,0.0000,NaN,0.1249,0.0732,0.9896,NaN,NaN,0.12,0.1034,0.3333,0.3750,NaN,0.1026,0.0793,0.0000,NaN,reg oper account,block of flats,0.1022,Panel,No,3.0,0.0,3.0,0.0,-628.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,1.0,1.0
1723,102015,0,Cash loans,F,N,Y,0,1935000.0,269550.0,10534.5,225000.0,Unaccompanied,Pensioner,Secondary / secondary special,Married,House / apartment,0.007114,-18636,365243,-3401.0,-2168,NaN,1,0,0,1,1,0,NaN,2.0,2,2,MONDAY,11,0,0,0,0,0,0,XNA,0.658977,0.268663,0.331251,0.0742,0.0495,0.9871,NaN,NaN,0.08,0.0690,0.3333,NaN,NaN,NaN,0.0716,NaN,NaN,0.0756,0.0514,0.9871,NaN,NaN,0.0806,0.0690,0.3333,NaN,NaN,NaN,0.0746,NaN,NaN,0.0749,0.0495,0.9871,NaN,NaN,0.08,0.0690,0.3333,NaN,NaN,NaN,0.0729,NaN,NaN,NaN,block of flats,0.0659,Panel,No,1.0,0.0,1.0,0.0,-381.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1793,102097,0,Revolving loans,F,Y,Y,1,540000.0,540000.0,27000.0,540000.0,Unaccompanied,Commercial associate,Higher education,Separated,House / apartment,0.032561,-11355,-2289,-4025.0,-2933,16.0,1,1,0,1,0,0,NaN,2.0,1,1,TUESDAY,18,0,0,0,0,0,0,Other,0.317398,0.757275,NaN,0.0206,0.0000,0.9518,0.3404,0.0106,0.00,0.1724,0.0833,0.1250,0.0705,0.0168,0.0432,0.0000,0.0000,0.0210,0.0000,0.9518,0.3662,0.0107,0.0000,0.1724,0.0833,0.1250,0.0721,0.0184,0.0450,0.0000,0.0000,0.0208,0.0000,0.9518,0.3492,0.0107,0.00,0.1724,0.0833,0.1250,0.0717,0.0171,0.0440,0.0000,0.0000,reg oper account,block of flats,0.0340,"Stone, brick",No,0.0,0.0,0.0,0.0,-1014.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1942,102276,0,Revolving loans,M,Y,Y,0,540000.0,315000.0,15750.0,450000.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.072508,-12613,-2747,-3410.0,-4383,5.0,1,1,1,1,0,0,Managers,2.0,1,1,THURSDAY,14,0,0,0,0,0,0,Trade: type 2,0.342913,0.735432,0.670652,0.0732,0.0358,0.9752,0.6600,0.0744,0.04,0.0345,0.3333,0.3750,0.0000,0.0597,0.0504,0.0000,0.0045,0.0746,0.0372,0.9752,0.6733,0.0751,0.0403,0.0345,0.3333,0.3750,0.0000,0.0652,0.0525,0.0000,0.0048,0.0739,0.0358,0.9752,0.6645,0.0748,0.04,0.0345,0.3333,0.3750,0.0000,0.0607,0.0513,0.0000,0.0046,reg oper account,block of flats,0.0407,Block,No,5.0,0.0,5.0,0.0,-127.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,2.0,2.0
1959,102297,0,Cash loans,M,Y,Y,2,675000.0,848745.0,46174.5,675000.0,Family,Commercial associate,Secondary / secondary special,Married,House / apartment,0.046220,-16483,-2082,-1824.0,-10,6.0,1,1,0,1,0,1,Drivers,4.0,1,1,SATURDAY,14,0,0,0,0,1,1,Business Entity Type 3,0.643478,0.589684,0.434733,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
2009,102356,0,Cash loans,M,Y,Y,1,765000.0,1350000.0,51552.0,1350000.0,Unaccompanied,Working,Incomplete higher,Separated,House / apartment,0.010643,-10186,-3012,-4912.0,-2857,7.0,1,1,0,1,0,0,NaN,2.0,2,2,SATURDAY,15,0,1,1,0,0,0,Business Entity Type 3,0.344301,0.655970,0.362277,0.0711,0.0291,0.9707,0.5988,0.0222,0.00,0.2414,0.1667,0.1667,0.0582,0.0563,0.0935,0.0077,0.0711,0.0725,0.0302,0.9707,0.6145,0.0224,0.0000,0.2414,0.1667,0.1667,0.0595,0.0615,0.0974,0.0078,0.0753,0.0718,0.0291,0.9707,0.6042,0.0223,0.00,0.2414,0.1667,0.1667,0.0592,0.0573,0.0952,0.0078,0.0726,reg oper account,block of flats,0.1011,"Stone, brick",No,1.0,0.0,1.0,0.0,-1752.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,2.0,1.0
2378,102782,0,Cash loans,F,N,Y,0,693000.0,835380.0,40320.0,675000.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.046220,-10076,-1773,-4874.0,-2557,NaN,1,1,0,1,0,0,NaN,2.0,1,1,SATURDAY,15,0,1,1,0,0,0,Business Entity Type 3,0.404878,0.550118,0.304672,0.0722,NaN,0.9767,NaN,NaN,0.00,0.1379,0.1667,NaN,0.1241,NaN,NaN,NaN,NaN,0.0735,NaN,0.9767,NaN,NaN,0.0000,0.1379,0.1667,NaN,0.1269,NaN,NaN,NaN,NaN,0.0729,NaN,0.9767,NaN,NaN,0.00,0.1379,0.1667,NaN,0.1262,NaN,NaN,NaN,NaN,NaN,block of flats,0.0568,"Stone, brick",No,2.0,0.0,2.0,0.0,-889.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
2843,103318,0,Cash loans,F,N,Y,2,540000.0,2156400.0,59301.0,1800000.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.046220,-13091,-2721,-2655.0,-5196,NaN,1,1,1,1,1,0,Managers,4.0,1,1,FRIDAY,16,1,1,0,1,1,0,Business Entity Type 3,0.519643,0.705339,0.231439,NaN,NaN,0.9965,0.9524,NaN,0.24,0.1034,0.6250,0.6667,NaN,NaN,0.2365,NaN,0.3962,NaN,NaN,0.9965,0.9543,NaN,0.2417,0.1034,0.6250,0.6667,NaN,NaN,0.2464,NaN,0.4194,NaN,NaN,0.9965,0.9530,NaN,0.24,0.1034,0.6250,0.6667,NaN,NaN,0.2407,NaN,0.4045,reg oper account,block of flats,0.2721,Monolithic,No,4.0,0.0,4.0,0.0,-835.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
2852,103328,0,Cash loans,F,N,Y,1,540000.0,2156400.0,57015.0,1800000.0,Children,Commercial associate,Higher education,Married,House / apartment,0.046220,-17900,-1824,-2235.0,-1451,NaN,1,1,0,1,0,1,Accountants,3.0,1,1,SATURDAY,11,0,1,1,0,0,0,Business Entity Type 3,0.767791,0.736405,0.239226,0.0495,0.0630,0.9752,0.6600,0.0000,0.00,0.1379,0.1250,0.1667,NaN,0.0403,0.0409,0.0000,0.0000,0.0504,0.0653,0.9752,0.6733,0.0000,0.0000,0.1379,0.1250,0.1667,NaN,0.0441,0.0426,0.0000,0.0000,0.0500,0.0630,0.9752,0.6645,0.0000,0.00,0.1379,0.1250,0.1667,NaN,0.0410,0.0416,0.0000,0.0000,reg oper account,block of flats,0.0345,"Stone, brick",No,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0